version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run tests
          command: go test -v ./...
